### ISSUE TITLE
"CLI interface, oghliner as a template/tool" live tests failing

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#283]
The "live" tests appear to be failing. For example, in https://travis-ci.org/mozilla/oghliner/jobs/148361426, I see:

```
  CLI interface, oghliner as a template
…
Username: Password: 
  Checking credentials…
✓ Checking credentials… done!
  Getting Travis token…
✗ Getting Travis token… error!
Forbidden

  1) should work
  2) "after all" hook
…
  62 passing (2m)
  4 failing
  1) CLI interface, oghliner as a template should work:
     Error: the number 1 was thrown, throw an Error :)
      at run (node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
…
```

**Comment by mykmelez** [comment]
I've worked around this for now by disabling the tests in 73c05e0.
